### ISSUE TITLE
Config option to disable the console output

### ISSUE THREAD

**Issue by JaHollTV** [LuftigerLuca/SyncedWeather#8]
Hey there,

i have a little feature request: Could you please add a config option to disable the output in the console?
"[09:24:26 INFO]: [SyncedWeather] [STDOUT] Setting weather to Clear"

For Servers with many plugins and players, every extra message in the console makes searching for errors a mess.

Thanks!

**Comment by LuftigerLuca** [comment]
Hey @JaHollTV,

thanks for opening this issue. I removed this debug message completely because I forgot to delete it from the code during the programming process.

Thanks very much :)
